"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { ars } from "@/lib/format";
import type { CashRegisterSummary } from "@/lib/types";

export default function CashRegisterSummaryPage() { const params = useParams<{ cashRegisterId: string }>(); const router = useRouter(); const [summary, setSummary] = useState<CashRegisterSummary | null>(null); const [error, setError] = useState(""); const [demo, setDemo] = useState(false); useEffect(() => { fetch(`/api/caja/${params.cashRegisterId}/resumen`).then(async (response) => { const body = await response.json(); if (body.ok) { setSummary(body.data); setDemo(Boolean(body.meta?.demo)); } else setError(body.error?.message || "No se pudo cargar el resumen."); }).catch(() => setError("No se pudo cargar el resumen.")); }, [params.cashRegisterId]); return <AppShell title="Resumen de caja" demo={demo} showFab={false}>{error && <div className="alert error">{error}</div>}{summary && <><div className="card dashboard-card"><div className="inline-row"><h2 style={{ margin: 0 }}>{summary.cashRegister.name}</h2><span className={`status-pill ${summary.cashRegister.status === "Abierta" ? "ok" : "missing"}`}>{summary.cashRegister.status}</span></div><div className="summary-grid" style={{ marginTop: 15 }}><div className="summary-item"><span>Inicial</span><strong>{ars(summary.cashRegister.initialCash)}</strong></div><div className="summary-item"><span>Ventas</span><strong>{ars(summary.totalSales)}</strong></div><div className="summary-item"><span>Esperado</span><strong>{ars(summary.expectedCash)}</strong></div><div className="summary-item"><span>Contado</span><strong>{summary.cashCounted === null || summary.cashCounted === undefined ? "Pendiente" : ars(summary.cashCounted)}</strong></div><div className="summary-item"><span>Diferencia</span><strong>{summary.difference === null || summary.difference === undefined ? "Pendiente" : ars(summary.difference)}</strong></div></div></div>{summary.warnings.map((warning) => <div className="alert info" key={warning}>{warning}</div>)}<div className="card dashboard-card"><h3 style={{ marginTop: 0 }}>Ventas por cuenta</h3>{summary.salesByAccount.map((item) => <div className="setting-row" key={item.accountId || item.accountName}><span>{item.accountName}{item.isCash ? " · efectivo" : " · no efectivo"}</span><strong>{ars(item.total)}</strong></div>)}</div>{summary.cashRegister.status === "Abierta" && <button className="primary-btn" onClick={() => router.push(`/caja/${params.cashRegisterId}/cerrar`)}>Cerrar caja</button>}</>}</AppShell>; }
