"use client";

import { FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { ars } from "@/lib/format";
import type { CashRegisterSummary } from "@/lib/types";

export default function CloseCashRegisterPage() {
  const router = useRouter(); const params = useParams<{ cashRegisterId: string }>(); const [summary, setSummary] = useState<CashRegisterSummary | null>(null); const [cashCounted, setCashCounted] = useState(""); const [notes, setNotes] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [demo, setDemo] = useState(false);
  useEffect(() => { fetch(`/api/caja/${params.cashRegisterId}/resumen`).then(async (response) => { const body = await response.json(); if (body.ok) { setSummary(body.data); setDemo(Boolean(body.meta?.demo)); setCashCounted(String(body.data.expectedCash || 0)); } else setError(body.error?.message || "No se pudo cargar el resumen."); }).catch(() => setError("No se pudo cargar el resumen.")); }, [params.cashRegisterId]);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); const response = await fetch(`/api/caja/${params.cashRegisterId}/cerrar`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ cashCounted: Number(cashCounted), notes }) }); const body = await response.json().catch(() => ({})); setSaving(false); if (!body.ok) return setError(body.error?.message || "No se pudo cerrar la caja."); router.replace("/caja"); }
  const difference = summary ? Number(cashCounted || 0) - summary.expectedCash : 0;
  return <AppShell title="Cerrar caja" demo={demo} showFab={false}><form className="card form-card" onSubmit={submit}>{summary && <><div className="summary-grid"><div className="summary-item"><span>Efectivo inicial</span><strong>{ars(summary.cashRegister.initialCash)}</strong></div><div className="summary-item"><span>Ventas efectivo</span><strong>{ars(summary.cashSales)}</strong></div><div className="summary-item"><span>Esperado efectivo</span><strong>{ars(summary.expectedCash)}</strong></div></div>{summary.estimated && <div className="alert info">El resumen es estimado porque falta la relación Movimientos → Caja.</div>}{summary.warnings.map((warning) => <div className="alert info" key={warning}>{warning}</div>)}</>}<div className="form-field"><label htmlFor="cash-counted">Efectivo contado</label><input id="cash-counted" required min="0" step="0.01" type="number" inputMode="decimal" value={cashCounted} onChange={(event) => setCashCounted(event.target.value)} /></div><div className="total-preview"><span>Diferencia</span><strong className={difference === 0 ? "money positive" : "money negative"}>{ars(difference)}</strong></div><div className="form-field"><label htmlFor="close-notes">Observación <span className="muted">(opcional)</span></label><textarea id="close-notes" value={notes} onChange={(event) => setNotes(event.target.value)} /></div>{error && <div className="alert error">{error}</div>}<button className="danger-btn" disabled={saving || !summary}>{saving ? "Cerrando…" : "Confirmar cierre"}</button><button type="button" className="secondary-btn" style={{ marginTop: 8 }} onClick={() => router.push("/caja")}>Cancelar</button></form></AppShell>;
}
