import { demoVariants } from "@/lib/demo-data";
import type { PendingReplenishment, ReplenishmentInput } from "@/lib/types";
import { readDemoPosState, updateDemoPosState } from "@/lib/demo-pos-state";

export function listDemoPendingReplenishments() { return readDemoPosState().replenishments.filter((item) => item.confirmationStatus === "Pendiente").map((item) => ({ ...item })); }
export function listDemoVariants() { const state = readDemoPosState(); return demoVariants.map((variant) => ({ ...variant, ...state.variantOverrides[variant.id] })); }
export function getDemoVariant(id: string) { const variant = demoVariants.find((item) => item.id === id); const state = readDemoPosState(); return variant ? { ...variant, ...state.variantOverrides[id] } : undefined; }
export function adjustDemoVariantStock(id: string, delta: number) { return updateDemoPosState((state) => { const variant = demoVariants.find((item) => item.id === id); if (!variant) return undefined; const currentStock = state.variantOverrides[id]?.currentStock ?? variant.currentStock; state.variantOverrides[id] = { ...state.variantOverrides[id], currentStock: currentStock + delta }; return { ...variant, ...state.variantOverrides[id] }; }); }
export function createDemoReplenishment(input: ReplenishmentInput, userId?: string) { const variant = getDemoVariant(input.variantId); if (!variant) throw new Error("VARIANT_NOT_FOUND"); return updateDemoPosState((state) => { const currentStock = state.variantOverrides[input.variantId]?.currentStock ?? variant.currentStock; state.variantOverrides[input.variantId] = { ...state.variantOverrides[input.variantId], currentStock: currentStock + input.quantity }; const item: PendingReplenishment = { id: `demo-replenishment-${Date.now()}`, movementId: `demo-replenishment-movement-${Date.now()}`, variantId: input.variantId, variantName: variant.name, businessId: input.businessId, date: input.date, quantity: input.quantity, currentCost: variant.replacementCost, costUsed: input.unitCost, reportedCost: input.reportedCost ?? null, confirmationStatus: input.confirmationStatus || "Pendiente", notes: input.notes || input.description || null, receivedByUserId: userId, warnings: [] }; state.replenishments = [item, ...state.replenishments]; return { ...item }; }); }
export function getDemoReplenishment(id: string) { return readDemoPosState().replenishments.find((item) => item.id === id); }
export function confirmDemoReplenishment(id: string, costUsed: number, updateMasterCost: boolean, userId?: string, notes?: string) { return updateDemoPosState((state) => { const item = state.replenishments.find((candidate) => candidate.id === id); if (!item) throw new Error("REPLENISHMENT_NOT_FOUND"); if (item.confirmationStatus !== "Pendiente") throw new Error("REPLENISHMENT_NOT_PENDING"); item.costUsed = costUsed; item.confirmationStatus = "Confirmado"; item.confirmedByUserId = userId; item.confirmedAt = new Date().toISOString(); if (notes) item.notes = notes; if (updateMasterCost) state.variantOverrides[item.variantId] = { ...state.variantOverrides[item.variantId], replacementCost: costUsed }; return { ...item, updateMasterCost }; }); }
export function rejectDemoReplenishment(id: string, userId?: string, notes?: string) { return updateDemoPosState((state) => { const item = state.replenishments.find((candidate) => candidate.id === id); if (!item) throw new Error("REPLENISHMENT_NOT_FOUND"); if (item.confirmationStatus !== "Pendiente") throw new Error("REPLENISHMENT_NOT_PENDING"); const variant = demoVariants.find((candidate) => candidate.id === item.variantId); if (variant) { const currentStock = state.variantOverrides[item.variantId]?.currentStock ?? variant.currentStock; state.variantOverrides[item.variantId] = { ...state.variantOverrides[item.variantId], currentStock: Math.max(0, currentStock - item.quantity) }; } item.confirmationStatus = "Rechazado"; item.confirmedByUserId = userId; item.confirmedAt = new Date().toISOString(); item.reversalMovementId = `demo-reversal-${Date.now()}`; if (notes) item.notes = notes; return { ...item, reversalMovementId: item.reversalMovementId }; }); }
