import type { CashRegisterSession, CashRegisterSummary, CloseCashRegisterInput, OpenCashRegisterInput } from "@/lib/types";
import { canAccessBusiness, isBusinessSeller, isGlobalAdmin, type PermissionSession } from "@/lib/permissions";
import { readDemoPosState, updateDemoPosState } from "@/lib/demo-pos-state";

export function listDemoCashRegisters(session: PermissionSession, filters: { status?: string } = {}) { return readDemoPosState().registers.filter((caja) => { if (filters.status && filters.status !== "todas" && caja.status.toLowerCase() !== filters.status.toLowerCase()) return false; if (isBusinessSeller(session) && caja.openedByUserId !== session.userId) return false; return isGlobalAdmin(session) || !caja.businessId || canAccessBusiness(session, caja.businessId); }).map((caja) => ({ ...caja })); }
export function getDemoOpenCashRegister(session: PermissionSession) { return listDemoCashRegisters(session, { status: "Abierta" }).find((caja) => caja.openedByUserId === session.userId && caja.businessId === session.activeBusinessId) || null; }
export function openDemoCashRegister(session: PermissionSession, input: OpenCashRegisterInput) { if (getDemoOpenCashRegister(session)) throw new Error("CASH_REGISTER_ALREADY_OPEN"); const now = new Date().toISOString(); const caja: CashRegisterSession = { id: `demo-cash-${Date.now()}`, name: `Caja ${new Date().toLocaleDateString("es-AR")}`, businessId: session.activeBusinessId, status: "Abierta", openedAt: now, openedByUserId: session.userId, cashAccountId: input.accountId, initialCash: input.initialCash, expectedCash: input.initialCash, cashCounted: null, difference: null, totalSales: 0, notes: input.notes || null }; updateDemoPosState((state) => { state.registers = [caja, ...state.registers]; }); return { data: { ...caja }, warnings: [] }; }
export function getDemoCashSummary(session: PermissionSession, cashRegisterId: string): CashRegisterSummary { const state = readDemoPosState(); const caja = state.registers.find((item) => item.id === cashRegisterId); if (!caja) throw new Error("CASH_REGISTER_NOT_FOUND"); if (!isGlobalAdmin(session) && caja.businessId && !canAccessBusiness(session, caja.businessId)) throw new Error("BUSINESS_FORBIDDEN"); const sales = state.sales.filter((sale) => sale.cashRegisterId === caja.id); const byAccount = new Map<string, { accountId?: string; accountName: string; total: number; isCash: boolean }>(); for (const sale of sales) { const item = byAccount.get(sale.accountId) || { accountId: sale.accountId, accountName: sale.accountId === "demo-cash" ? "Efectivo" : "Cuenta", total: 0, isCash: sale.accountId === caja.cashAccountId }; item.total += sale.total; byAccount.set(sale.accountId, item); } const salesByAccount = [...byAccount.values()]; const cashSales = salesByAccount.filter((item) => item.isCash).reduce((sum, item) => sum + item.total, 0); const nonCashSales = salesByAccount.filter((item) => !item.isCash).reduce((sum, item) => sum + item.total, 0); const expectedCash = caja.initialCash + cashSales; return { cashRegister: { ...caja, expectedCash, totalSales: cashSales + nonCashSales }, totalSales: cashSales + nonCashSales, salesByAccount, cashSales, nonCashSales, expectedCash, cashCounted: caja.cashCounted, difference: caja.cashCounted === null || caja.cashCounted === undefined ? null : caja.cashCounted - expectedCash, estimated: false, warnings: [] }; }
export function recordDemoSale(cashRegisterId: string, accountId: string, total: number, date: string, userId?: string) { return updateDemoPosState((state) => { const movementId = `demo-pos-movement-${Date.now()}-${state.sales.length}`; state.sales.push({ movementId, cashRegisterId, accountId, total, date, userId }); return movementId; }); }
export function closeDemoCashRegister(session: PermissionSession, cashRegisterId: string, input: CloseCashRegisterInput) { const caja = readDemoPosState().registers.find((item) => item.id === cashRegisterId); if (!caja) throw new Error("CASH_REGISTER_NOT_FOUND"); if (caja.status !== "Abierta") throw new Error("CASH_REGISTER_NOT_OPEN"); if (!isGlobalAdmin(session) && caja.businessId && !canAccessBusiness(session, caja.businessId)) throw new Error("BUSINESS_FORBIDDEN"); if (isBusinessSeller(session) && caja.openedByUserId !== session.userId) throw new Error("CASH_REGISTER_FORBIDDEN"); const summary = getDemoCashSummary(session, cashRegisterId); const difference = input.cashCounted - summary.expectedCash; const result = updateDemoPosState((state) => { const target = state.registers.find((item) => item.id === cashRegisterId); if (!target) throw new Error("CASH_REGISTER_NOT_FOUND"); Object.assign(target, { status: "Cerrada", closedAt: new Date().toISOString(), closedByUserId: session.userId, cashCounted: input.cashCounted, expectedCash: summary.expectedCash, difference, totalSales: summary.totalSales, notes: input.notes || target.notes }); return { ...target }; }); return { data: { ...summary, cashCounted: input.cashCounted, difference, cashRegister: result }, warnings: [] }; }
export function assertDemoCashRegister(session: PermissionSession, cashRegisterId: string) { const caja = readDemoPosState().registers.find((item) => item.id === cashRegisterId); if (!caja) throw new Error("CASH_REGISTER_NOT_FOUND"); if (caja.status !== "Abierta") throw new Error("CASH_REGISTER_NOT_OPEN"); if (!isGlobalAdmin(session) && caja.businessId && !canAccessBusiness(session, caja.businessId)) throw new Error("BUSINESS_FORBIDDEN"); if (isBusinessSeller(session) && caja.openedByUserId !== session.userId) throw new Error("CASH_REGISTER_FORBIDDEN"); return caja; }
