"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import type { Account } from "@/lib/types";
import { ars } from "@/lib/format";

export default function OpenCashRegisterPage() {
  const router = useRouter(); const [accounts, setAccounts] = useState<Account[]>([]); const [accountId, setAccountId] = useState(""); const [initialCash, setInitialCash] = useState("0"); const [notes, setNotes] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [demo, setDemo] = useState(false);
  useEffect(() => { fetch("/api/cuentas").then(async (response) => { const body = await response.json(); if (body.ok) { setAccounts(body.data || []); setAccountId(body.data?.find((account: Account) => account.isMainCash)?.id || body.data?.[0]?.id || ""); setDemo(Boolean(body.meta?.demo)); } else setError(body.error?.message || "No se pudieron cargar las cuentas."); }).catch(() => setError("No se pudieron cargar las cuentas.")); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); const response = await fetch("/api/caja/abrir", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ accountId, initialCash: Number(initialCash), notes }) }); const body = await response.json().catch(() => ({})); setSaving(false); if (!body.ok) return setError(body.error?.message || "No se pudo abrir la caja."); router.replace("/caja"); }
  return <AppShell title="Abrir caja" demo={demo} showFab={false}><form className="card form-card" onSubmit={submit}><p className="small muted" style={{ marginTop: 0 }}>Una caja abierta queda asociada a tu usuario y negocio activo.</p><div className="form-field"><label htmlFor="cash-account">Cuenta efectivo</label><select id="cash-account" required value={accountId} onChange={(event) => setAccountId(event.target.value)}><option value="">Seleccionar cuenta</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}{account.isMainCash ? " · principal" : ""}</option>)}</select>{!accounts.length && <span className="small muted">No hay cuentas activas para este negocio.</span>}</div><div className="form-field"><label htmlFor="initial-cash">Efectivo inicial</label><input id="initial-cash" required min="0" step="0.01" type="number" inputMode="decimal" value={initialCash} onChange={(event) => setInitialCash(event.target.value)} /></div><div className="form-field"><label htmlFor="open-notes">Notas <span className="muted">(opcional)</span></label><textarea id="open-notes" value={notes} onChange={(event) => setNotes(event.target.value)} /></div><div className="total-preview"><span>Inicio del turno</span><strong>{ars(Number(initialCash) || 0)}</strong></div>{error && <div className="alert error">{error}</div>}<button className="primary-btn" disabled={saving || !accounts.length}>{saving ? "Abriendo…" : "Abrir caja"}</button><button type="button" className="secondary-btn" style={{ marginTop: 8 }} onClick={() => router.push("/caja")}>Cancelar</button></form></AppShell>;
}
