"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import type { PublicUser } from "@/lib/notion/user-admin";
import { AccessDenied } from "@/components/access-denied";

export default function UsersPage() { const router = useRouter(); const [users, setUsers] = useState<PublicUser[]>([]); const [showInactive, setShowInactive] = useState(false); const [demo, setDemo] = useState(false); const [loading, setLoading] = useState(true); const [denied, setDenied] = useState(false); const [error, setError] = useState("");
  async function load() { setLoading(true); const response = await fetch(`/api/usuarios?includeInactive=${showInactive}`); const body = await response.json(); if (response.status === 401) return router.replace("/login"); if (response.status === 403) setDenied(true); else if (!body.ok) setError(body.error?.message || "No se pudieron cargar los usuarios."); else { setUsers(body.data || []); setDemo(Boolean(body.meta?.demo)); setError(""); } setLoading(false); }
  useEffect(() => { load(); }, [showInactive]);
  async function toggle(user: PublicUser) { const response = await fetch(`/api/usuarios/${user.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: user.active === false }) }); const body = await response.json(); if (!body.ok) return setError(body.error?.message || "No se pudo actualizar el usuario."); load(); }
  async function reset(user: PublicUser) { if (!window.confirm("Esto borrará el PIN actual. La próxima vez el usuario deberá crear uno nuevo.")) return; const response = await fetch(`/api/usuarios/${user.id}/reset-pin`, { method: "POST" }); const body = await response.json(); if (!body.ok) return setError(body.error?.message || "No se pudo restaurar el PIN."); load(); }
  if (denied) return <AccessDenied title="Usuarios" />;
  if (loading) return <AppShell title="Usuarios" demo={demo}><div className="skeleton" style={{ marginTop: 14 }} /><div className="skeleton" style={{ marginTop: 12 }} /></AppShell>;
  return <AppShell title="Usuarios" demo={demo} showFab={false}><div className="admin-actions"><button className="primary-btn" onClick={() => router.push("/usuarios/nuevo")}>+ Nuevo usuario</button><button className="secondary-btn" onClick={() => router.push("/config")}>Ver schema en Config</button></div><label className="check-row"><input type="checkbox" checked={showInactive} onChange={(event) => setShowInactive(event.target.checked)} /> Mostrar usuarios inactivos</label>{error && <div className="alert error">{error}</div>}<div className="product-list">{users.map((user) => <article className={`card account-admin-card ${user.active === false ? "inactive-card" : ""}`} key={user.id}><div className="inline-row"><div><strong>{user.name}</strong><span className="product-subtitle">{user.role} · {user.active === false ? "Inactivo" : "Activo"}</span></div><span className={`status-pill ${user.active === false ? "missing" : "ok"}`}>{user.hasPin ? "PIN configurado" : "PIN pendiente"}</span></div>{user.lastLogin && <p className="small muted">Último acceso: {new Date(user.lastLogin).toLocaleString("es-AR")}</p>}{user.notes && <p className="small muted">{user.notes}</p>}<div className="product-actions"><button className="primary-btn" onClick={() => router.push(`/usuarios/${user.id}/editar`)}>Editar</button><button className="secondary-btn" onClick={() => reset(user)}>Restaurar PIN</button><button className={user.active === false ? "secondary-btn" : "danger-btn"} onClick={() => toggle(user)}>{user.active === false ? "Reactivar" : "Desactivar"}</button></div></article>)}{!users.length && <div className="card dashboard-card"><p className="small muted" style={{ margin: 0 }}>No hay usuarios para mostrar.</p></div>}</div></AppShell>;
}
