"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import type { Account, Debtor } from "@/lib/types";
const today = () => new Date().toISOString().slice(0, 10);
export default function IncomePage() { const router = useRouter(); const [kind, setKind] = useState("general"); const [accounts, setAccounts] = useState<Account[]>([]); const [debtors, setDebtors] = useState<Debtor[]>([]); const [form, setForm] = useState({ amount: "", accountId: "", date: today(), description: "", debtorId: "" }); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { const params = new URLSearchParams(window.location.search); const initialKind = params.get("kind") || "general"; const debtorId = params.get("deudor") || ""; setKind(initialKind); setForm((f) => ({ ...f, debtorId })); Promise.all([fetch("/api/cuentas"), fetch("/api/deudores")]).then(async ([a, d]) => { const ab = await a.json(); const db = await d.json(); if (ab.ok) { setAccounts(ab.data); setForm((f) => ({ ...f, accountId: f.accountId || ab.data[0]?.id || "" })); } if (db.ok) setDebtors(db.data); }); }, []);
  async function submit(e: FormEvent) { e.preventDefault(); setMessage(""); setError(""); setSaving(true); const response = await fetch(kind === "debt" ? "/api/movimientos/cobro-deuda" : "/api/movimientos/ingreso", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, amount: Number(form.amount), kind }) }); const body = await response.json(); setSaving(false); if (!body.ok) return setError(body.error?.message || "No se pudo guardar."); setMessage(body.meta?.message || "Movimiento guardado correctamente."); setTimeout(() => router.push("/movimientos"), 700); }
  return <AppShell title={kind === "debt" ? "Cobro de deuda" : "Cargar ingreso"} showFab={false}><form className="card form-card" onSubmit={submit}><div className="form-field"><label htmlFor="income-kind">Tipo de ingreso</label><select id="income-kind" value={kind} onChange={(e) => setKind(e.target.value)}><option value="general">Ingreso general</option><option value="simple">Venta simple sin producto</option><option value="debt">Cobro de deuda</option></select></div>{kind === "debt" && <div className="form-field"><label htmlFor="debtor">Deudor</label><select id="debtor" value={form.debtorId} onChange={(e) => setForm({ ...form, debtorId: e.target.value })}><option value="">Seleccionar deudor</option>{debtors.filter((d) => d.balance > 0).map((d) => <option key={d.id} value={d.id}>{d.name} · {new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 }).format(d.balance)}</option>)}</select></div>}<div className="form-field"><label htmlFor="income-amount">Monto</label><input id="income-amount" required min="1" step="1" inputMode="decimal" type="number" placeholder="0" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></div><div className="form-field"><label htmlFor="income-account">Cuenta</label><select id="income-account" required value={form.accountId} onChange={(e) => setForm({ ...form, accountId: e.target.value })}><option value="">Seleccionar cuenta</option>{accounts.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select></div><div className="form-field"><label htmlFor="income-date">Fecha</label><input id="income-date" required type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></div><div className="form-field"><label htmlFor="income-description">Descripción <span className="muted">(opcional)</span></label><textarea id="income-description" placeholder="Ej. Venta mostrador" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div>{error && <div className="alert error">{error}</div>}{message && <div className="alert success">{message}</div>}<button className="primary-btn" disabled={saving}>{saving ? "Guardando…" : "Guardar movimiento"}</button></form></AppShell>; }
