"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { AccessDenied } from "@/components/access-denied";
import { ars } from "@/lib/format";
import type { CashRegisterSession } from "@/lib/types";

export default function CashRegistersPage() { const router = useRouter(); const [items, setItems] = useState<CashRegisterSession[]>([]); const [demo, setDemo] = useState(false); const [error, setError] = useState(""); const [denied, setDenied] = useState(false); useEffect(() => { fetch("/api/cajas").then(async (response) => { const body = await response.json(); if (response.status === 403) setDenied(true); else if (body.ok) { setItems(body.data || []); setDemo(Boolean(body.meta?.demo)); } else setError(body.error?.message || "No se pudieron cargar las cajas."); }).catch(() => setError("No se pudieron cargar las cajas.")); }, []); if (denied) return <AccessDenied title="Historial de cajas" />; return <AppShell title="Historial de cajas" demo={demo} showFab={false}><div className="admin-actions"><button className="primary-btn" onClick={() => router.push("/caja")}>Caja actual</button></div>{error && <div className="alert error">{error}</div>}<div className="product-list">{items.map((caja) => <article className="card account-admin-card" key={caja.id}><div className="inline-row"><div><strong>{caja.name}</strong><span className="product-subtitle">{caja.openedAt ? new Date(caja.openedAt).toLocaleString("es-AR") : ""} · {caja.businessId || "Negocio activo"}</span></div><span className={`status-pill ${caja.status === "Abierta" ? "ok" : "missing"}`}>{caja.status}</span></div><div className="stock-grid"><div><span>Efectivo inicial</span><strong>{ars(caja.initialCash)}</strong></div><div><span>Diferencia</span><strong>{caja.difference === null || caja.difference === undefined ? "Pendiente" : ars(caja.difference)}</strong></div></div><button className="secondary-btn" onClick={() => router.push(`/caja/${caja.id}/resumen`)}>Ver resumen</button></article>)}{!items.length && <div className="card dashboard-card"><p className="small muted" style={{ margin: 0 }}>No hay cajas para mostrar.</p></div>}</div></AppShell>; }
