"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import type { Account, AccountInput } from "@/lib/types";

type AccountSchema = { typeField?: { name: string; type: string; options: string[] }; activeProperty?: string; mainCashProperty?: string; initialBalanceProperty?: string; orderProperty?: string; notesProperty?: string };

const emptyForm: AccountInput = { name: "", type: "", initialBalance: 0, isMainCash: false, active: true, order: null, notes: "" };

export function AccountForm({ accountId }: { accountId?: string }) {
  const router = useRouter(); const editing = Boolean(accountId); const [form, setForm] = useState<AccountInput>(emptyForm); const [schema, setSchema] = useState<AccountSchema>({}); const [demo, setDemo] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");

  useEffect(() => { fetch("/api/cuentas?includeInactive=true").then(async (response) => { const body = await response.json(); if (response.status === 401) return router.replace("/login"); if (!body.ok) { setError(body.error?.message || "No se pudo cargar la configuración de Cuentas."); setLoading(false); return; } setSchema(body.meta?.schema || {}); setDemo(Boolean(body.meta?.demo)); if (accountId) { const account = (body.data || []).find((item: Account) => item.id === accountId); if (!account) setError("No se encontró la cuenta."); else setForm({ name: account.name, type: account.type || "", initialBalance: account.initialBalance, isMainCash: account.isMainCash === true, active: account.active !== false, order: account.order ?? null, notes: account.notes || "" }); } setLoading(false); }).catch(() => { setError("No se pudo cargar la cuenta."); setLoading(false); }); }, [accountId, router]);

  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); setMessage(""); const response = await fetch(accountId ? `/api/cuentas/${accountId}` : "/api/cuentas", { method: accountId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); setSaving(false); if (!body.ok) return setError(body.error?.message || (accountId ? "No se pudo actualizar la cuenta." : "No se pudo crear la cuenta.")); setMessage(body.meta?.message || "Cuenta guardada correctamente."); setTimeout(() => router.push("/cuentas"), 700); }

  async function toggleActive() { if (!accountId) return; setSaving(true); const response = await fetch(`/api/cuentas/${accountId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: form.active === false }) }); const body = await response.json(); setSaving(false); if (!body.ok) return setError(body.error?.message || "No se pudo actualizar el estado de la cuenta."); setForm((current) => ({ ...current, active: current.active === false })); setMessage(demo ? "Guardado simulado en modo demo." : form.active === false ? "Cuenta reactivada." : "Cuenta desactivada. No se elimina de Notion."); }

  if (loading) return <AppShell title="Cuenta" showFab={false}><div className="skeleton" style={{ marginTop: 14 }} /></AppShell>;
  const typeField = schema.typeField; const canEditActive = Boolean(schema.activeProperty); const canEditMainCash = Boolean(schema.mainCashProperty); const canEditInitial = Boolean(schema.initialBalanceProperty); const canEditOrder = Boolean(schema.orderProperty); const canEditNotes = Boolean(schema.notesProperty);
  return <AppShell title={editing ? "Editar cuenta" : "Nueva cuenta"} demo={demo} showFab={false}><form className="card form-card" onSubmit={submit}><div className="form-field"><label htmlFor="account-name">Nombre</label><input id="account-name" required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Ej. Efectivo, Banco, billetera…" /></div>{typeField && <div className="form-field"><label htmlFor="account-type">Tipo de cuenta</label>{(typeField.type === "select" || typeField.type === "status") && typeField.options.length ? <select id="account-type" value={form.type || ""} onChange={(event) => setForm({ ...form, type: event.target.value })}><option value="">Sin tipo</option>{typeField.options.map((option) => <option key={option} value={option}>{option}</option>)}</select> : <input id="account-type" value={form.type || ""} onChange={(event) => setForm({ ...form, type: event.target.value })} placeholder="Texto libre" />}</div>}{canEditInitial && <div className="form-field"><label htmlFor="account-initial">Saldo inicial</label><input id="account-initial" required min="0" step="0.01" type="number" value={form.initialBalance ?? 0} onChange={(event) => setForm({ ...form, initialBalance: Number(event.target.value) })} /></div>}{canEditMainCash && <label className="check-row"><input type="checkbox" checked={form.isMainCash === true} onChange={(event) => setForm({ ...form, isMainCash: event.target.checked })} /> Es caja principal</label>}{canEditActive && <label className="check-row"><input type="checkbox" checked={form.active !== false} onChange={(event) => setForm({ ...form, active: event.target.checked })} /> Cuenta activa</label>}{canEditOrder && <div className="form-field"><label htmlFor="account-order">Orden <span className="muted">(opcional)</span></label><input id="account-order" type="number" value={form.order ?? ""} onChange={(event) => setForm({ ...form, order: event.target.value === "" ? null : Number(event.target.value) })} /></div>}{canEditNotes && <div className="form-field"><label htmlFor="account-notes">Notas <span className="muted">(opcional)</span></label><textarea id="account-notes" value={form.notes || ""} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></div>}{editing && <div className="alert info">Saldo esperado se calcula automáticamente con los movimientos. Para corregir saldo, ajustá saldo inicial o cargá un movimiento de ajuste.</div>}{error && <div className="alert error">{error}</div>}{message && <div className="alert success">{message}</div>}<button className="primary-btn" disabled={saving}>{saving ? "Guardando…" : editing ? "Guardar cambios" : "Crear cuenta"}</button>{editing && canEditActive && <button type="button" className={form.active === false ? "secondary-btn" : "danger-btn"} style={{ marginTop: 10 }} onClick={toggleActive} disabled={saving}>{form.active === false ? "Reactivar cuenta" : "Desactivar cuenta"}</button>}</form></AppShell>;
}
