"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import type { ReactNode } from "react";
import { canViewConfig } from "@/lib/permissions";

const nav = [{ href: "/", label: "Resumen", icon: "⌂", visible: () => true }, { href: "/movimientos", label: "Movimientos", icon: "↕", visible: (session: any) => !session || !session.role || !session.role.includes("Vendedor") }, { href: "/cargar", label: "Cargar", icon: "+", visible: () => true }, { href: "/deudores", label: "Deudores", icon: "♙", visible: (session: any) => !session || !session.role || !session.role.includes("Vendedor") }, { href: "/config", label: "Config", icon: "⚙", visible: (session: any) => !session || canViewConfig(session) }];
export function AppShell({ title, children, demo = false, showFab = true }: { title: string; children: ReactNode; demo?: boolean; showFab?: boolean }) {
  const pathname = usePathname(); const router = useRouter(); const [session, setSession] = useState<{ userName: string; role: string; authMode: string; activeBusinessId?: string } | null>(null); const [businesses, setBusinesses] = useState<Array<{ id: string; name: string }>>([]);
  useEffect(() => { fetch("/api/auth/session").then((response) => response.json()).then((body) => { if (body.data?.authenticated) { setSession(body.data.session); if (body.data.session.role === "Admin global" || body.data.session.role === "Admin negocio") fetch("/api/negocios").then((response) => response.json()).then((businessBody) => setBusinesses(businessBody.data || [])).catch(() => undefined); } }).catch(() => undefined); }, []);
  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); router.replace("/login"); }
  async function switchBusiness(businessId: string) { const response = await fetch("/api/session/active-business", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ businessId }) }); if (response.ok) { setSession((current) => current ? { ...current, activeBusinessId: businessId } : current); router.refresh(); } }
  const visibleNav = nav.filter((item) => item.visible(session));
  return <main className="app-frame mobile-width"><header className="top-header"><div className="inline-row"><div><div className="eyebrow">Finanzas El Tigre</div><h1>{title}</h1>{session && <div className="session-chip">Sesión: {session.userName} · {session.role}{session.authMode === "legacy" ? " · Legacy" : ""}</div>}</div><button aria-label="Cerrar sesión" onClick={logout} style={{ background: "transparent", border: 0, color: "white", fontSize: 20 }}>↪</button></div>{session && businesses.length > 1 && <select aria-label="Negocio activo" value={session.activeBusinessId || ""} onChange={(event) => switchBusiness(event.target.value)} style={{ marginTop: 8, width: "100%" }}>{businesses.map((business) => <option key={business.id} value={business.id}>{business.name}</option>)}</select>}</header>{demo && <div className="demo-banner">Modo demo: faltan variables de Notion</div>}<section className="page-body">{children}</section>{showFab && <button className="fab" aria-label="Cargar movimiento" onClick={() => router.push("/cargar")}>+</button>}<nav className="bottom-nav">{visibleNav.map((item) => { const active = item.href === "/" ? pathname === "/" : pathname.startsWith(item.href); return <Link href={item.href} className={`nav-item ${active ? "active" : ""}`} key={item.href}><span className="nav-icon">{item.icon}</span><span>{item.label}</span></Link>; })}</nav></main>;
}
