"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { ars } from "@/lib/format";
import type { Account } from "@/lib/types";

export default function AccountsPage() {
  const router = useRouter(); const [accounts, setAccounts] = useState<Account[]>([]); const [showInactive, setShowInactive] = useState(false); const [demo, setDemo] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); const response = await fetch(`/api/cuentas?includeInactive=${showInactive}`); const body = await response.json(); if (response.status === 401) return router.replace("/login"); if (!body.ok) setError(body.error?.message || "No se pudieron cargar las cuentas."); else { setAccounts(body.data || []); setDemo(Boolean(body.meta?.demo)); setError(""); } setLoading(false); }
  useEffect(() => { load(); }, [showInactive]);
  const total = useMemo(() => accounts.reduce((sum, account) => sum + (account.expectedBalance ?? account.balance ?? account.initialBalance), 0), [accounts]);
  async function toggle(account: Account) { const response = await fetch(`/api/cuentas/${account.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: account.active === false }) }); const body = await response.json(); if (!body.ok) return setError(body.error?.message || "No se pudo actualizar la cuenta."); await load(); }
  if (loading) return <AppShell title="Cuentas" demo={demo}><div className="skeleton" style={{ marginTop: 14 }} /><div className="skeleton" style={{ marginTop: 12 }} /></AppShell>;
  return <AppShell title="Cuentas" demo={demo}><div className="admin-actions"><button className="primary-btn" onClick={() => router.push("/cuentas/nueva")}>+ Nueva cuenta</button><button className="secondary-btn" onClick={() => router.push("/config")}>Ver schema en Config</button></div><div className="account-summary"><div><span>{showInactive ? "Cuentas mostradas" : "Cuentas activas"}</span><strong>{accounts.length}</strong></div><div><span>Saldo esperado total</span><strong>{ars(total)}</strong></div></div><label className="check-row"><input type="checkbox" checked={showInactive} onChange={(event) => setShowInactive(event.target.checked)} /> Mostrar cuentas inactivas</label>{error && <div className="alert error">{error}</div>}<div className="product-list">{accounts.map((account) => { const expected = account.expectedBalance ?? account.balance ?? account.initialBalance; return <article className={`card account-admin-card ${account.active === false ? "inactive-card" : ""}`} key={account.id}><div className="inline-row"><div><strong>{account.name}</strong><span className="product-subtitle">{[account.type, account.isMainCash ? "Caja principal" : "", account.active === false ? "Inactiva" : "Activa"].filter(Boolean).join(" · ")}</span></div><span className={`status-pill ${account.active === false ? "missing" : "ok"}`}>{account.active === false ? "Inactiva" : "Activa"}</span></div><div className="stock-grid"><div><span>Saldo esperado</span><strong>{ars(expected)}</strong></div><div><span>Saldo inicial</span><strong>{ars(account.initialBalance)}</strong></div></div>{account.notes && <p className="small muted">{account.notes}</p>}<div className="product-actions"><button className="primary-btn" onClick={() => router.push(`/cuentas/${account.id}/editar`)}>Editar</button><button className={account.active === false ? "secondary-btn" : "danger-btn"} onClick={() => toggle(account)}>{account.active === false ? "Reactivar" : "Desactivar"}</button></div></article>; })}{!accounts.length && <div className="card dashboard-card"><p className="small muted" style={{ margin: 0 }}>{showInactive ? "No hay cuentas configuradas." : "No hay cuentas activas. Creá una cuenta para poder cargar movimientos."}</p></div>}</div></AppShell>;
}
