"use client";

import { useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { AccessDenied } from "@/components/access-denied";
import { ars } from "@/lib/format";
import type { PendingReplenishment } from "@/lib/types";

type Named = { id: string; name: string };

export default function PendingReplenishmentsPage() {
  const [items, setItems] = useState<PendingReplenishment[]>([]); const [users, setUsers] = useState<Named[]>([]); const [businesses, setBusinesses] = useState<Named[]>([]); const [loading, setLoading] = useState(true); const [denied, setDenied] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [demo, setDemo] = useState(false);
  async function load() { setLoading(true); const response = await fetch("/api/reposiciones-pendientes"); const body = await response.json().catch(() => ({})); if (response.status === 403) setDenied(true); else if (!body.ok) setError(body.error?.message || "No se pudieron cargar las reposiciones pendientes."); else { setItems(body.data || []); setDemo(Boolean(body.meta?.demo)); setError(""); } setLoading(false); }
  useEffect(() => { Promise.all([fetch("/api/reposiciones-pendientes"), fetch("/api/usuarios?includeInactive=true"), fetch("/api/negocios")]).then(async ([pendingResponse, usersResponse, businessesResponse]) => { const pendingBody = await pendingResponse.json().catch(() => ({})); const usersBody = await usersResponse.json().catch(() => ({})); const businessesBody = await businessesResponse.json().catch(() => ({})); if (pendingResponse.status === 403) setDenied(true); else if (!pendingBody.ok) setError(pendingBody.error?.message || "No se pudieron cargar las reposiciones pendientes."); else { setItems(pendingBody.data || []); setDemo(Boolean(pendingBody.meta?.demo)); } setUsers(usersBody.ok ? (usersBody.data || []) : []); setBusinesses(businessesBody.ok ? (businessesBody.data || []) : []); setLoading(false); }).catch(() => { setError("No se pudieron cargar las reposiciones pendientes."); setLoading(false); }); }, []);
  async function confirm(item: PendingReplenishment, updateMasterCost: boolean) { const cost = Number((document.getElementById(`cost-${item.id}`) as HTMLInputElement)?.value); const notes = (document.getElementById(`notes-${item.id}`) as HTMLTextAreaElement)?.value || ""; setError(""); const response = await fetch(`/api/reposiciones-pendientes/${item.id}/confirmar`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ costUsed: cost, updateMasterCost, notes }) }); const body = await response.json().catch(() => ({})); if (!body.ok) return setError(body.error?.message || "No se pudo confirmar la reposición."); setMessage(body.meta?.message || "Reposición confirmada."); await load(); }
  async function reject(item: PendingReplenishment) { const notes = (document.getElementById(`notes-${item.id}`) as HTMLTextAreaElement)?.value || ""; if (!window.confirm("La reposición quedará rechazada y se intentará compensar el stock con un ajuste inverso.")) return; const response = await fetch(`/api/reposiciones-pendientes/${item.id}/rechazar`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ notes }) }); const body = await response.json().catch(() => ({})); if (!body.ok) return setError(body.error?.message || "No se pudo rechazar la reposición."); setMessage(body.meta?.message || "Reposición rechazada."); await load(); }
  const nameOf = (list: Named[], id?: string) => list.find((item) => item.id === id)?.name || id || "No informado";
  if (denied) return <AccessDenied title="Reposiciones pendientes" />;
  if (loading) return <AppShell title="Reposiciones pendientes" demo={demo} showFab={false}><div className="skeleton" style={{ marginTop: 14 }} /><div className="skeleton" style={{ marginTop: 12 }} /></AppShell>;
  return <AppShell title="Reposiciones pendientes" demo={demo} showFab={false}><p className="small muted">Revisá las recepciones de stock antes de confirmar el costo definitivo.</p>{error && <div className="alert error">{error}</div>}{message && <div className="alert success">{message}</div>}<div className="product-list">{items.map((item) => <article className="card dashboard-card" key={item.id}><div className="inline-row"><div><strong>{item.variantName}</strong><span className="product-subtitle">{item.date} · {item.quantity} unidades</span></div><span className="status-pill missing">Pendiente</span></div><div className="small" style={{ lineHeight: 1.7, marginTop: 10 }}><div>Negocio: <strong>{nameOf(businesses, item.businessId)}</strong></div><div>Costo actual registrado: <strong>{ars(item.currentCost)}</strong></div><div>Costo nuevo informado: <strong>{item.reportedCost ? ars(item.reportedCost) : "No informado"}</strong></div><div>Recibido por: <strong>{nameOf(users, item.receivedByUserId)}</strong></div></div><div className="form-field"><label htmlFor={`cost-${item.id}`}>Costo usado definitivo</label><input id={`cost-${item.id}`} type="number" min="0.01" step="0.01" defaultValue={item.reportedCost || item.costUsed || item.currentCost} /></div><div className="form-field"><label htmlFor={`notes-${item.id}`}>Observación</label><textarea id={`notes-${item.id}`} defaultValue={item.notes || ""} placeholder="Factura, corrección o motivo…" /></div><div className="product-actions"><button className="primary-btn" onClick={() => confirm(item, false)}>Confirmar sin cambiar costo maestro</button><button className="secondary-btn" onClick={() => confirm(item, true)}>Confirmar y actualizar costo maestro</button><button className="danger-btn" onClick={() => reject(item)}>Rechazar / anular</button></div></article>)}{!items.length && <div className="card dashboard-card"><p className="small muted" style={{ margin: 0 }}>No hay reposiciones pendientes.</p></div>}</div></AppShell>;
}
